### ISSUE TITLE
Material gets cleaned wen you paint

### ISSUE THREAD

**Issue by Janders1800** [tomankirilov/VPainter#3] opened 2020-04-21 17:55 UTC
Wen you paint the surface of a mesh, the material gets unset on the inspector.
Possible related to: #2

**Comment by tomankirilov** [comment] 2020-07-26 07:36
In Godot there are two ways of adding a material to a mesh. On the mesh itself or on the MeshInstance node.
If you add the material on the mesh instance node for some reason it gets cleaned even though I don't touch it.
I suspect it's because I change the mesh itself (my addon creates a duplicate of the original mesh).
You can add the material to the mesh itself.
For the other problem - I am still looking for a solution.

**Closed as completed** 2022-06-16 17:38 UTC
